name: CustomItemLoader
author: alvin0319
main: alvin0319\CustomItemLoader\CustomItemLoader
version: 2.0.6
api: 3.0.0

mcpe-protocol: 440

permissions:
  customitemloader.command.rsc:
    default: op
  customitemloader.command:
    default: op